/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.champeau.gradle.advisories

/**
 * A simple unit test for the 'me.champeau.gradle.advisories' plugin.
 */
class AdvisoriesGradlePluginTest {


}
