/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.champeau.gradle.advisories

import org.gradle.testkit.runner.GradleRunner
import java.io.File
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'me.champeau.gradle.advisories.greeting' plugin.
 */
class AdvisoriesGradlePluginPluginFunctionalTest {
    @Test fun `can run task`() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id 'me.champeau.gradle.advisories'
                id 'java-library'
            }
            
            repositories {
               jcenter()
            }
            
            dependencies {
                implementation 'org.apache.hadoop:hadoop-main:2.9.0'
            }
            
            tasks.register("resolve") {
                inputs.files(configurations.compileClasspath)
                doLast {
                    println configurations.compileClasspath.files
                }
            }
        """)

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("resolve")
        runner.withProjectDir(projectDir)
        runner.withDebug(true)
        val result = runner.build();

        // Verify the result
        assertTrue(result.output.contains("Hello from plugin 'me.champeau.gradle.advisories.greeting'"))
    }
}
